name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
  workflow_dispatch:

env:
  CI: true

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache gradle, wrapper and buildSrc
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan/cache
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
            ~/.konan/kotlin-native-mingw*
            ~/.konan/kotlin-native-windows*
            ~/.konan/kotlin-native-linux*
            ~/.konan/kotlin-native-prebuilt-macos*
            ~/.konan/kotlin-native-prebuilt-mingw*
            ~/.konan/kotlin-native-prebuilt-windows*
            ~/.konan/kotlin-native-prebuilt-linux*
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run iosX64 tests
        run: ./gradlew iosX64Test --stacktrace

      - name: Run Tests
        run: ./gradlew koverMergedXmlReport

      - name: Upload Test Report
        uses: codecov/codecov-action@v3.1.3
